### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by codescrawl** [fukamachi/ningle#10]
Hi,

I was a little stumped whilst trying to figure out params in the examples given and found this - it might be worth amending.

The documentation says this:

(setf (ningle:route *app* "/hello/:name")
      #'(lambda (params)
          (format nil "Hello, ~A" (assoc "name" params :test #'string=))))

but I had to change it to this to get it working:

(setf (ningle:route *app* "/hello/:name")
      #'(lambda (params)
	  (format nil "Hello, ~@A" (cdr (assoc :name params)))))

Note the addition of the cdr function and use of a keyword parameter rather than a string. When I used the original it didn't find anything unless I capitalized the string which felt bad to me.

Feel free to ignore or set me right if I've missed something.

**Comment by 1u4nx** [comment]
Yes, and this error also happening in http://8arrow.org/ningle/ :-(

**Comment by fukamachi** [comment]
Fixed.
