### ISSUE TITLE
How to access *request* and *response*

### ISSUE THREAD

**Issue by tgallant** [fukamachi/ningle#11]
Hi I'm just starting out with your library. Thanks for all the hard work!

the documentation says 

`ningle provides two special variables named *request* and *response*. They will be bound to an instance Clack.Request and Clack.Response for each request.`

can you provide an example of how to access these variables? I am trying to set the Content-Type to json

Thanks for the help

**Comment by fukamachi** [comment]
Sorry, the README was old.
The latest ningle uses Clack v2 APIs and `*request*` and `*response*` are `Lack.Request` and `Lack.Response`.

You can set `Content-Type` header like this:

```common-lisp
(setf (lack.response:headers *response*)
      (append (lack.response:headers *response*)
              (list :content-type "application/json")))
```

**Comment by tgallant** [comment]
this solves my issue. thanks!

**Comment by mooseyboots** [comment]
hi, i'm also just starting out with your library and i'm having the same issue. 

where would this code actually go relative to a `(ningle:route)` call? i'm trying to start using parenscript in my ningle project and need to handle "text/javascript" content-type. if i place it within a lambda i receive an error that *response* is unbound.

```
(setf (ningle:route *app* "/parenscript-example.js")
      #'(lambda (params)
;; tried setting it here, followed by hello world parenscript fun:
            (parenscript:ps
                  (defun greeting-cb ()
                      (alert "hello there!")))))
```
