### ISSUE TITLE
Readme is confusing with "authorize"

### ISSUE THREAD

**Issue by sabracrolleton** [fukamachi/ningle#16]
The Readme leaves me confused with the login method in the usage section. Where does "authorize" come from?

**Comment by fukamachi** [comment]
Define by yourself as you like.

**Comment by sabracrolleton** [comment]
Thank you. I thought maybe it was referencing something I could not find.

I appreciate all your work on these libraries.

Sabra

On Mon, Sep 19, 2016 at 12:27 AM, Eitaro Fukamachi <notifications@github.com
