### ISSUE TITLE
how to use cl-who or djula with ningle

### ISSUE THREAD

**Issue by arademaker** [fukamachi/ningle#18]
The  ```(djula:render-template ... )``` needs a stream as parameter, how to capture the stream to write the template output?

**Comment by fukamachi** [comment]
Look at `with-output-to-stream`.

**Comment by arademaker** [comment]
Hum, not clear if I understood your comment. Anyway, I was able to produce the output directly with

```
(setf (ningle:route *app* "/hello/:name")
      #'(lambda (params)
	  (djula:render-template* +base.html+ nil
				  :title (cdr (assoc :name params))
				  :message "teste")))
```
