### ISSUE TITLE
Params list is truncated

### ISSUE THREAD

**Issue by mpsota** [fukamachi/ningle#22]
I think the commit 3e60411f62668ca79c681b9cc6549f78826c6a88 affects the params list not only for multipart/form-data but also for other requests.

Test case:

```
(defun handle (params)
  (format t "~&~a~%" params))
(setf (ningle:route *app* "/test" :method :post)
      #'handle)
```
```
curl -H "Content-Type: application/json" -X POST -d '{"args":[1,2,3]}' localhost:8083/test
```

prints: `((args . 1))` instead of expected `((args 1 2 3))`. It works fine before that commit.

Regards,
Michał

**Comment by dkochmanski** [comment]
this issue may be closed, fixed in the version taken from quicklisp
