### ISSUE TITLE
How do I properly set cookies?

### ISSUE THREAD

**Issue by nathanvy** [fukamachi/ningle#43]
I can set cookies using the `:headers` property in `ningle:*response*, but if I try to use `:set-cookies` which is also part of the response struct, it just silently fails.  I can see in the browser console no cookies are set:

```lisp
(setf (lack.response:response-set-cookies ningle:*response*)
                "foobar=barbaz")
```

<img width="1068" alt="Screenshot 2023-08-29 at 11 24 54 PM" src="https://github.com/fukamachi/ningle/assets/2128134/14ca409a-dad1-4318-87a0-b1569714734f">

What is the correct way to set cookies?

**Comment by fukamachi** [comment]
`response-set-cookies` must be a property list that has a key as the name and a value as a property list containing `:value`, `:domain`, `:path`, `:expires`, `:secure`, `:httponly`, and `:samesite`.

ex. `("foobar" (:value "barbaz"))`

Here the code of Lack.Response: https://github.com/fukamachi/lack/blob/master/src/response.lisp#L44

**Comment by nathanvy** [comment]
Thanks.  I had found the code previously, but reading it did not provide me with any clarity.  I appreciate the response.
